image: archlinux
packages:
    - nodejs
    - yarn
sources:
    - https://git.sr.ht/~siarune/urmom
tasks:
    - setup: |
        cd urmom
        yarn install
        yarn add vercel
        yarn pullConfig
    - build: |
        cd urmom
        yarn buildProd
    - deploy: |
        cd urmom
        yarn deploy
